name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Default nightly
      run: rustup default nightly
    - name: Run test
      run: cargo test --verbose
    - name: Run build
      run: cargo build --verbose
